### ISSUE TITLE
Miss train_seld_foa.sh in script folder

### ISSUE THREAD

**Issue by PaulWU1996** [sony/audio-visual-seld-dcase2023#1]
Hi. I found that train_seld_foa.sh needs to be added to the script folder. Also, no files in the list_dataset folder support mic-type files. Would you like to help us to fix this problem when you are free? Cheers.

**Comment by kaz-shimada** [comment]
Thank you for spotting the bugs. Now I fixed the script name and added lists for mic in [the latest commit](https://github.com/sony/audio-visual-seld-dcase2023/commit/1ccc68fc65b06637dba0bdd8f34f2fab7b83bfdb). Please check it.

**Comment by PaulWU1996** [comment]
Hi Shimada

Many thanks for your email; I will check the MIC branch today. I completed
one train_script for FOA and trained it well. Looking forward to seeing the
script for MIC type. Cheers.

Best wishes,
Peipei
